### PR TITLE
Update core/res/res/layout/keyguard_screen_unlock_landscape.xml

### PR DESCRIPTION
**Pull request by travp624**
Fixes Face unlock lockscreen!

### CODE REVIEW

**Comment by netboy3** [comment]
This patch just removes sethy's weather update from the lockscreen layout. I'm not a layout expert, but I wouldn't merge this without first making sure there is no other way of getting the layout right.

**Comment by travp624** [comment]
There probably is a better way but this was a quick fix for now if needed. I'm certainly not nowhere as skilled as the teamkang guys!

**Comment by sethyx** [comment]
I know what the problem is here, don't merge it, fix commit incoming today.

**Comment by sethyx** [comment]
fix committed: https://github.com/sethyx/frameworks_base/commit/6e3b21beccf45fd0292e561453fc13ab7f9a401c
this can be closed.

**Pull request closed without merging**
