### PR TITLE
Update core/res/res/layout/keyguard_screen_unlock_portrait.xml

### PR DESCRIPTION
**Pull request by travp624**
Fixes face unlock portrait!

### CODE REVIEW

**Comment by netboy3** [comment]
This patch just removes sethy's weather update from the lockscreen layout. I'm not a layout expert, but I wouldn't merge this without first making sure there is no other way of getting the layout right.

**Comment by travp624** [comment]
There probably is a better way but this was a quick fix for now if needed. I'm certainly not nowhere as skilled as the teamkang guys!

**Comment by sethyx** [comment]
Did you test it? I mean, did you compile after this change, and face unlock worked?

**Comment by sethyx** [comment]
Ok, I know what the problem is here, don't merge it, fix commit incoming today.

**Comment by sethyx** [comment]
Btw face unlock works, it's just not visible. Keyguard tries to render it to the wrong place.
You can check it if you disable weather@lockscreen: http://dl.dropbox.com/u/7965056/Screenshot_2012-02-28-09-17-03.png
I hope I can fix this, as faceunlock is closed source, and if it's set somewhere in the already compiled modules, we can't do anything about it.

**Comment by sethyx** [comment]
fix committed: https://github.com/sethyx/frameworks_base/commit/6e3b21beccf45fd0292e561453fc13ab7f9a401c
this can be closed.

**Pull request closed without merging**
